### ISSUE TITLE
Trace trap on macos M2 ONLY on keyboard events

### ISSUE THREAD

**Issue by cobbledtogether** [justDeeevin/NuhxBoard#10]
Using `main` at the time of this (commit 2684284). On Macbook pro M2 Ventura 13.0. Runtime crashes with Trace trap on any keyboard event. I'm printing out the event in the `listen` thread to investigate, but it crashes before then. 

https://github.com/user-attachments/assets/b025966a-73d9-42fa-a338-04024ae01add

Note, running a separate mini rust program with only `rdev` (version 0.5.3) works fine
![image](https://github.com/user-attachments/assets/8b729025-d67c-4ed8-be33-50453f2637f8)

**Comment by justDeeevin** [comment]
This isn't with the feature `grab`, is it?

**Comment by justDeeevin** [comment]
ohp, the print statement is in the no-grab block. nvm

**Comment by justDeeevin** [comment]
What's `KeyboardState` here?

**Comment by cobbledtogether** [comment]
I've set up a minimal example with an `rdev`-`Subscription`. This gives me the same issue. `rdev` by itself works fine though. So I suspect the issue is with the `iced::channel`. I will experiment some more and let you know if I find the issue.  See minimal example here https://github.com/cbbldtgthr/keygraph/blob/master/src/main.rs

**Comment by cobbledtogether** [comment]
I'm going to assume that this is the issue. As proposed here, a separate `rdev` "key-server" process will be best. I'm going to build my own version with a WebSocket server. 
![image](https://github.com/user-attachments/assets/265ab4be-ec32-4a02-a144-24a1ed94bad4)
https://www.reddit.com/r/rust/comments/wskkia/global_keyboard_events/

**Comment by justDeeevin** [comment]
Good catch! I apologize for not finding this earlier--I haven't really had the opportunity to test on MacOS.
I'll start researching the separate process thing. I don't have a lot of time on my hands right now, though, so this might be a minute. For the time being, I'll update the README with a note on MacOS compaibility.
