### ISSUE TITLE
keyboard inputs crash nuhxboard on MacOS

### ISSUE THREAD

**Issue by mangeyv** [justDeeevin/NuhxBoard#9]
Nuhxboard shows an 'illegal hardware instruction' message and closes the app, after a key on a keyboard is pressed. Mouse inputs work fine. 

Is there anyway this could be fixed or is nuhxboard not yet optimised for MacOS.

**Comment by justDeeevin** [comment]
did you find a resolution to this? why did you close?

also, yes, I haven't fount the opportunity to effectively test NuhxBoard on MacOS yet.
